"""Criando relacionamento de Delete entre Tabelas User e tarefas

Revision ID: 0217c3538005
Revises: 7cc8a2d7fc75
Create Date: 2026-06-17 20:08:46.577323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0217c3538005'
down_revision: Union[str, Sequence[str], None] = '7cc8a2d7fc75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefas', schema=None) as batch_op:
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_tarefas_responsavel_id', 'user_account', ['responsavel_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tarefas_responsavel_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_account', ['responsavel_id'], ['id'])

    # ### end Alembic commands ###
