"""alterando coluna tel para email

Revision ID: 084188f24db8
Revises: ee91f713ecfd
Create Date: 2026-06-05 09:53:05.817092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084188f24db8'
down_revision: Union[str, Sequence[str], None] = 'ee91f713ecfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
