"""Criando valor default = False na coluna receber_mensagem

Revision ID: 56b4dc18937a
Revises: ec6603df45c4
Create Date: 2026-06-09 19:30:32.615758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b4dc18937a'
down_revision: Union[str, Sequence[str], None] = 'ec6603df45c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
