"""Nullable = False p/ user e tarefas

Revision ID: 58d6dbeee468
Revises: 0217c3538005
Create Date: 2026-06-18 21:15:49.554596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58d6dbeee468'
down_revision: Union[str, Sequence[str], None] = '0217c3538005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.alter_column('user', nullable=False)
        batch_op.alter_column('email', nullable=True)
        batch_op.create_unique_constraint('uq_user_account_email', ['email'])
        batch_op.create_unique_constraint('uq_user_account_user', ['user'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_ck', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_ck', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_constraint('uq_user_account_user', type_='unique')
        batch_op.drop_constraint('uq_user_account_email', type_='unique')
        batch_op.drop_column('email')
        batch_op.drop_column('user')

    # ### end Alembic commands ###
