"""Adicionando create-at em User

Revision ID: 7616f4216e24
Revises: 58d6dbeee468
Create Date: 2026-06-20 14:10:54.783854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7616f4216e24'
down_revision: Union[str, Sequence[str], None] = '58d6dbeee468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarefas', schema=None) as batch_op:
        batch_op.alter_column('responsavel_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('tarefas_responsavel_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('tarefas', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('tarefas_responsavel_id_fkey'), 'user_account', ['responsavel_id'], ['id'])
        batch_op.alter_column('responsavel_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
