"""Criando valor default = False na coluna receber_mensagem

Revision ID: 7cc8a2d7fc75
Revises: 56b4dc18937a
Create Date: 2026-06-09 19:34:36.741536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cc8a2d7fc75'
down_revision: Union[str, Sequence[str], None] = '56b4dc18937a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
    
               UPDATE user_account SET receber_mensagem = '0' where receber_mensagem is NULL
    """)
       

    # ### end Alembic commands ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
