"""Criando coluna booleana para envio de mensagem

Revision ID: ec6603df45c4
Revises: 084188f24db8
Create Date: 2026-06-09 19:15:01.122600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec6603df45c4'
down_revision: Union[str, Sequence[str], None] = '084188f24db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receber_mensagem', sa.Boolean(), server_default='False', nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_account', schema=None) as batch_op:
        batch_op.drop_column('receber_mensagem')

    # ### end Alembic commands ###
