services: # Onde os contêineres são declarados
  run_flask:
    build: .
    ports:
      - "8080:5000"
    env_file:
      - .env
    volumes:
      - ./data/:/usr/local/app/data

  scheduler:
    build: .
    env_file:
      - .env
    command: ["python", "scheduler.py"]
